### ISSUE TITLE
Indexed Access to List

### ISSUE THREAD

**Issue by smalls12** [abvdasker/crystal-linked-list#5]
I'm playing around learning crystal and wanted to use your linked list implementation.
I noticed it does not support index access ( not like it has to ), was wondering if you would accept a pull request if I got it working.
Thanks

**Comment by break2bits** [comment]
Go for it! As you probably noticed, I haven't touched this repo in a long time. Any improvements are welcome.

**Comment by smalls12** [comment]
Can be closed
