### ISSUE TITLE
Stack and Queue

### ISSUE THREAD

**Issue by smalls12** [abvdasker/crystal-linked-list#8]
I'm looking at expanding this for doubly linked list and for also providing stack and queue implementations with the linked list.

Juts wondered what your thoughts were.

Could we expand this repo into a more generic data structure project.

**Comment by break2bits** [comment]
I like the idea of an expanded set of data structures for Crystal, but I'm not sure this repo is the best place for it. If you create a repo for Crystal data structures, you're welcome to take as much or as little of this repo's code as you want.
